apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- external-secret.yaml
- configmap.yaml

commonLabels:
  app.kubernetes.io/name: guitartortona-api
  app.kubernetes.io/component: backend
  app.kubernetes.io/managed-by: argocd

images:
- name: ghcr.io/mmzitarosa/guitartortona-api
  newTag: latest  # Overridden by overlays
