apiVersion: v1
kind: Service
metadata:
  name: guitartortona-api
  namespace: staging
  labels:
    app: guitartortona-api
    environment: staging
spec:
  selector:
    app: guitartortona-api
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
