apiVersion: v1
kind: Service
metadata:
  name: guitartortona-api
  labels:
    app: guitartortona-api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  - name: management
    port: 8081
    targetPort: management
    protocol: TCP
  selector:
    app: guitartortona-api
