apiVersion: apps/v1
kind: Deployment
metadata:
  name: guitartortona-api
  labels:
    environment: api-staging
    app.kubernetes.io/version: v1.2.0-rc9
spec:
  replicas: 1
  template:
    metadata:
      labels:
        environment: api-staging
        app.kubernetes.io/version: v1.2.0-rc9
    spec:
      containers:
        - name: guitartortona-api
          env:
            - name: ENVIRONMENT
              value: "staging"
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes,staging"
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m -XX:+UseG1GC -Djava.io.tmpdir=/tmp"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"