apiVersion: apps/v1
kind: Deployment
metadata:
  name: guitartortona-api
  labels:
    environment: production
    app.kubernetes.io/version: v1.2.0
spec:
  template:
    metadata:
      labels:
        environment: production
        app.kubernetes.io/version: v1.2.0
    spec:
      containers:
        - name: guitartortona-api
          env:
            - name: ENVIRONMENT
              value: "production"
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes,production"
            - name: JAVA_OPTS
              value: "-Xms512m -Xmx1024m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Djava.io.tmpdir=/tmp"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"