apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - external-secret-db.yaml
  - external-secret-ghcr.yaml

patchesStrategicMerge:
  - deployment-patch.yaml
  - deployment-version-label.yaml

commonLabels:
  environment: production
  app.kubernetes.io/part-of: guitartortona-api

images:
  - name: ghcr.io/mmzitarosa/guitartortona-api
    newTag: v1.2.0