apiVersion: v1
kind: Service
metadata:
  name: guitartortona-api
  labels:
    app.kubernetes.io/name: guitartortona-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: guitartortona-api
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: management
      port: 8081
      targetPort: management
      protocol: TCP